[mypy]
# 忽略因找不到模組型別存根 (stubs) 而產生的匯入錯誤
ignore_missing_imports = True
# 允許變數在同一範圍內被重新定義為不同型別
allow_redefinition = True
# 啟用增量模式
incremental = True
# 當 Mypy 本身崩潰時，顯示詳細的錯誤追蹤訊息
show_traceback = True
# 在整個專案中停用 arg-type 檢查
disable_error_code = arg-type
# 排除測試與 log 目錄
exclude = ^(tests/|logs/)
